CREATE TABLE pago_datos (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numero_tarjeta VARCHAR(19) NOT NULL,
    fecha_caducidad DATE NOT NULL,
    nombre_tarjeta VARCHAR(100) NOT NULL,
    cvv VARCHAR(4) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
